import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";

import "./globals.css";
import Providers from "@/components/Providers";
import StyledComponentsRegistry from "./registry";

const font = Instrument_Sans()

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${font.className} min-h-screen antialiased dark:bg-[#1F232A] dark:text-[#E6EDF3]`}
            >
                <Providers>
                    <StyledComponentsRegistry>
                        {children}
                    </StyledComponentsRegistry>
                </Providers>
            </body>
        </html>
    );
}
